spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: charts/guestbook
    repoURL: https://github.com/cwusyscrest/argocd-demo-helmfile
    targetRevision: HEAD

environment: dev
