{{- if .Values.server.configEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-cm
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
  {{- if .Values.server.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.server.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  configManagementPlugins: |
    - name: helmfile
      init:                          # Optional command to initialize application source directory
        command: ["argo-cd-helmfile.sh"]
        args: ["init"]
      generate:                      # Command to generate manifests YAML
        command: ["argo-cd-helmfile.sh"]
        args: ["generate"]
{{- toYaml .Values.server.config | nindent 4 }}
{{- end }}